version: '3.1'

services:
    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'root'
            MONGO_INITDB_ROOT_PASSWORD: 'action'
        ports:
            - 8081:27017
        volumes:
            - .dbdata:/data/db

    suchon_site:
        depends_on: 
            - mongo
        container_name: suchon_site
        build: 
            context: .
            dockerfile: Dockerfile
        # restart: always
        env_file: 
            - .env
        ports: 
            - 3001:3000
